services:
  automata:
    build: .
    container_name: automata
    ports:
      - "8010:8010"
    networks:
      - default
      - automata-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  automata-net:
    driver: bridge