# Radxa A7S Profile (Node Testing)
#spring.data.mongodb.host=mongodb
application.mqtt.url=tcp://hivemq-edge:1883
#application.mqtt.url=tcp://192.168.1.54:1884
spring.data.redis.host=redis
spring.data.redis.database=0
#application.rabbit_mq.url=tcp://192.168.1.54:61613
# Server MongoDB for Sync
spring.data.mongodb.uri=mongodb://admin:12345678@10.156.206.18:27017,mongodb:27017/automata?replicaSet=rs0&readPreference=nearest&authSource=admin
app.notification.ntfy.url=http://192.168.1.53:82/automata
application.env=radxa
#test