# Production Profile (Deployment)
spring.data.mongodb.host=mongodb
application.mqtt.url=tcp://hivemq-ce:1883
#application.mqtt.url=tcp://rabbitmq:1884
spring.data.redis.host=redis
spring.data.redis.database=0
#application.rabbit_mq.url=tcp://rabbitmq:61613
app.notification.ntfy.url=http://ntfy/automata