# Radxa A7S Profile (Node Testing)
spring.data.mongodb.host=mongodb
application.mqtt.url=tcp://hivemq:1883
#application.mqtt.url=tcp://192.168.1.54:1884
spring.data.redis.host=redis
spring.data.redis.database=0
#application.rabbit_mq.url=tcp://192.168.1.54:61613
# Server MongoDB for Sync
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=admin
spring.data.mongodb.password=12345678
app.notification.ntfy.url=http://192.168.1.53:82/automata
application.env=radxa